TaoxanhProxy/Models/DeviceMode.cs
namespace TaoxanhProxy.Models
{
    public class DeviceModel
    {
        public string? Id { get; set; }
        public Guid? UserId { get; set; }
        public string? Token { get; set; }
        public string? AndroidId { get; set; }
        public DeviceStatus? Status { get; set; }
        public DeviceSetting? Setting { get; set; }
        public Proxy? Proxy { get; set; }
        public string? Message  { get; set; } 
    }
    public enum DeviceStatus
    {
        Active, Pause, Approval, Delete
    }

    public class DeviceSetting
    {
        public bool? DebugMode { get; set; }
        public long? Time { get; set; }
        public string[]? AppRunning { get; set; }
    }
    public class Proxy
    {
        public string Id { get; set; }
        public string? Token { get; set; }
        public Guid? UserId { get; set; }
        public string? ProxyProfile { get; set; }
        public string? ProxyType { get; set; }
        public string? Ip { get; set; }
        public string? Username { get; set; }
        public string? Pasword { get; set; }
        public string? Port { get; set; }
        public string? Note { get; set; }
    }
}

TaoxanhProxy/Models/ProxyDeviceModel.cs
namespace TaoxanhProxy.Models
{
    public class ProxyDeviceModel
    {
        public string Id { get; set; } 
        public string? Name { get; set; }
        public string? Location { get; set; }
        public string? Table { get; set; }
        public string? Box { get; set; }
        public string? PID { get; set; } 
    }
}

TaoxanhProxy/Models/UserModel.cs
namespace TaoxanhProxy.Models
{
    public class UserModel
    {
        public string UserName { get; set; }
        public string Token { get; set; }
        public string AccessToken { get; set; }
        public long ExpiresIn { get; set; }
    }
}

TaoxanhProxy/Controllers/ProxyController.cs
using Microsoft.AspNetCore.Mvc;
using TaoxanhProxy.Models;
using TaoxanhProxy.Services;

namespace TaoxanhProxy.Controllers
{
    [ApiController]
    [Route("")]

    public class ProxyController : ControllerBase
    {
        private readonly IInternalService internalService;

        public ProxyController(IInternalService internalService)
        {
            this.internalService = internalService;
        }

        [HttpPost("check-proxy")]
        public async Task<bool?> CheckAsync(SetProxyDeviceRequestDto request)
        {
            return (await internalService.SetProxyForDeviceAsync(request.DeviceId)) != null;
        }
    }
}

TaoxanhProxy/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaoxanhProxy.Services;

namespace TaoXanhProxyWeb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IInternalService authService;

        public IndexModel(ILogger<IndexModel> logger, IInternalService authService)
        {
            _logger = logger;
            this.authService = authService;
        }

        public async Task<IActionResult> OnGet()
        {
            var user = await authService.GetCurrentUserAsync();
            if (user == null)
            {
                return RedirectToPage("./Login");
            }
            return RedirectToRoute("./Profile");
        }
    }
}

TaoxanhProxy/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaoxanhProxy.Services;

namespace TaoxanhProxy.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        public string Password { get; set; }
        [BindProperty]
        public string ErrorMessage { get; set; }
        private readonly IInternalService authService;

        public LoginModel(IInternalService authService)
        {
            this.authService = authService;
        }


        public void OnGet()
        {
            
        }
        public async Task OnPostLogin()
        {
            var res = await authService.AuthAsync(Username, Password);
            if (res)
            {
                ErrorMessage = string.Empty;
                Response.Redirect("./Profile");
            }
            ErrorMessage = "Incorect username or password";
        }
    }
}

TaoxanhProxy/Pages/Profile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaoxanhProxy.Models;
using TaoxanhProxy.Services;

namespace TaoxanhProxy.Pages
{
    public class ProfileModel : PageModel
    {
        private readonly IInternalService authService;

        [BindProperty]
        public UserModel? UserModel { get; set; }
        public ProfileModel(IInternalService authService)
        {
            this.authService = authService;
        }

        public async Task OnGet()
        {
            UserModel = await authService.GetCurrentUserAsync();
            if (UserModel == null)
            {
                Response.Redirect("./Login");
            }
        }

        public async Task<IActionResult> OnPostLogout()
        {
            await authService.LogoutAsync();
            return RedirectToPage("./Login");
        }
    }
}

TaoxanhProxy/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
} 
<!------ Include the above in your HEAD tag ---------->

 

TaoxanhProxy/Pages/Login.cshtml
@page
@model TaoxanhProxy.Pages.LoginModel
@{
}

<div class="vh-100 h-100">
    <div class="row  justify-content-center">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5">
                    <h5 class="card-title text-center mb-5 fw-light fs-5">Sign In</h5>
                    <form method="post">
                        <div class="form-floating mb-3">
                            <input asp-for="Username" type="Username" class="form-control" id="floatingInput" placeholder="your username">
                            <label for="floatingInput">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input asp-for="Password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <label class="text-danger">@Model.ErrorMessage</label>

                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit" asp-page-handler="Login">
                                Sign
                                in
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

TaoxanhProxy/Pages/Profile.cshtml
@page
@model TaoxanhProxy.Pages.ProfileModel
@{
}

<div class="vh-100 h-100">
    <div class="row  justify-content-center">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5">
                    <h5 class="card-title text-center mb-5 fw-light fs-5">Profile</h5>
                    <form method="post">
                        <div class="form-floating mb-3">
                            <input asp-for="UserModel.UserName" type="text" readonly class="form-control" placeholder="your username">
                            <label for="floatingInput">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input asp-for="UserModel.Token" type="text" readonly class="form-control" id="floatingToken" placeholder="Token">
                            <label for="floatingToken">Token</label>
                        </div>


                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit" asp-page-handler="LogOut">
                                Logout
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

TaoxanhProxy/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaoXanhProxy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> 
    <link href="TaoxanhProxy.styles.css" rel="stylesheet">
</head>
<body>

    <main role="main" class="container"> 
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>